# Generated by Django 4.2.1 on 2023-05-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_title',
            field=models.CharField(max_length=60, verbose_name='JobTitle'),
        ),
    ]
